### ISSUE TITLE
How to write solution printer callbacks in v0.9.8?

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#122]
In version 0.9.7 one could use the CPM_ortools attribute `varmap` to push all the decision variables to a solution printer callback but `varmap` is not available in 0.9.8.

E.g.

```
# ...
ss = CPM_ortools(model)
cb = solution_printer(ss.varmap,x,0)
```

But this now throws: `AttributeError: 'CPM_ortools' object has no attribute 'varmap'`

It seems that `user_vars` has replace `varmap`. Is that correct?

In 0.9,7 one then had to convert these variables to CPMpy variables with the following trick:
```
    for cpm_var in self.vars:
      cpm_var._value = self.Value(self.varmap[cpm_var])      
```

But that now just throws:
```
terminate called after throwing an instance of 'Swig::DirectorMethodException'
```
which mean that something is wrong. It actually throws an exception by just printing the `cpm_var`:
```
    for cpm_var in self.vars:
      print(cpm_var)
```

Here is a small example of this.
```
from cpmpy import *
from cpmpy.solvers import *
from ortools.sat.python import cp_model as ort

class solution_printer(ort.CpSolverSolutionCallback):
  """
  A simple printer callback for single array printing.
  """
  def __init__(self, varmap, a, num_solutions=0):
    super().__init__()
    self.solcount = 0
    self.varmap = varmap
    self.vars = (a)
    self.num_solutions=num_solutions

  def on_solution_callback(self):
    self.solcount += 1 # I always start at 1. :-) 

    # This does not work in 0.9.8
    # convert to cpmpy vars
    # for cpm_var in self.vars:
    #   cpm_var._value = self.Value(self.varmap[cpm_var])      
      
    # (a) = self.vars            
    # print(f"#{self.solcount}: {a.value()}")

    if self.num_solutions > 0 and self.solcount >= self.num_solutions:
      self.StopSearch()

def euler31():
   coins = [200,100,50,20,10,5,2,1]
   Max = max(coins)
   n = len(coins)
   x = intvar(0,Max,shape=n,name="x")
   model = Model(200 == sum(coins*x))

   ss = CPM_ortools(model)
   # cb = solution_printer(ss.varmap,x,0) # old version  that worked in 0.9.7
   cb = solution_printer(ss.user_vars,x,0)   

   ss.ort_solver.parameters.linearization_level = 0
   ss.ort_solver.parameters.cp_model_probing_level = 0
   
   ort_status = ss.ort_solver.SearchForAllSolutions(ss.ort_model, cb)
   print("Nr solutions:", cb.solcount)

euler31()
```

As it stand, this works since it just counts the solutions. But how do I print all the solutions in 0.9.8, i.e. replacing this commented code:
```
    # Convert to cpmpy vars
    # for cpm_var in self.vars:
    #   cpm_var._value = self.Value(self.varmap[cpm_var])      
      
    # (a) = self.vars            
    # print(f"#{self.solcount}: {a.value()}")
```

**Comment by tias** [comment]
Hey Hakan,

We made the interfaces more uniform and now have a function self.solver_var(), and we renamed self.varmap to self._varmap to discourage direct use of the varmap I think.

For your usecase, you do want to copy the datastructure, so self._varmap it is.

Note that we implemented a s.solveAll() that covers most use cases of solution enumeration/printing, see the docs here:
https://cpmpy.readthedocs.io/en/latest/multiple_solutions.html

so `cnt = model.solveAll(display=x)` should cover your case?

And for that, we implemented a callback like the one you have in your code, you can see its code here:
https://github.com/CPMpy/cpmpy/blob/908108db01181ba9d9482f2e574f554405b75f87/cpmpy/solvers/ortools.py#L548
